# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
# resolver: lts-12.11
# resolver: lts-11.22
resolver: lts-14.27
# resolver: nightly-2019-10-15

packages:
- pg-schema
- pg-schema-tutorial

# extra-deps:
# - git: https://github.com/odr/singletons.git
#   commit: ad8a595ab1811d0e7f17d6829b7edf29a7eaa96a
