{-# LANGUAGE NoDuplicateRecordFields #-}
{-# LANGUAGE NoOverloadedStrings #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE UndecidableSuperClasses #-}
{-# LANGUAGE ParallelListComp #-}
module PgSchema.Schema where

import Data.Coerce
import Data.Kind
import Data.List as L
import Data.List.Singletons as SP
import Data.Map as M
import Data.Ord.Singletons
import Data.Singletons.TH
import Data.String
import Data.Tagged
import Data.Text as T
import GHC.TypeLits
import PgSchema.Utils.Internal
import Prelude.Singletons as SP
import Text.Show.Singletons




singletons [d|
  data AggrFun = ACount | AMin | AMax | ASum | AAvg
    deriving (Show, Eq, Ord)

  data NameNS' s = NameNS
    { nnsNamespace  :: s
    , nnsName       :: s }
    deriving (Show, Eq, Ord)

  data TypDef' s = TypDef
    { typCategory :: s
    , typElem     :: Maybe (NameNS' s)
    , typEnum     :: [s] }
    deriving (Show, Eq)

  data FldDef' s = FldDef
    { fdType        :: NameNS' s
    , fdNullable    :: Bool
    , fdHasDefault  :: Bool }
    deriving (Show, Eq)

  data TabDef' s = TabDef
    { tdFlds       :: [s]
    , tdKey        :: [s]
    , tdUniq       :: [[s]] }
    deriving (Show, Eq)

  data RelDef' s = RelDef
    { rdFrom    :: NameNS' s
    , rdTo      :: NameNS' s
    , rdCols    :: [(s,s)] }
    deriving (Show, Eq)

  data RelType = RelOne | RelMany

  data RecField' s p
    = RFEmpty s
    | RFPlain (FldDef' s)
    | RFAggr (FldDef' s) AggrFun Bool
    -- True in RFAggr means: "Can be used in any selects",
    -- False means: "Can be used only in selects with GROUP BY"
    | RFToHere p [Ref' s]
    | RFFromHere p [Ref' s]
    deriving Show

  data Ref' s = Ref
    { fromName :: s -- db field name
    , fromDef  :: FldDef' s
    , toName   :: s
    , toDef    :: FldDef' s }
    deriving (Eq, Show)

  |]

promote [d|
  getRelTab
    :: Eq s
    => [(NameNS' s, RelDef' s)] -> [(NameNS' s, RelDef' s)] -> s
    -> (NameNS' s, RelType)
  getRelTab froms tos s = find1 froms
    where
      find1 []         = find2 tos
      find1 ((a,b):xs) = if nnsName a == s then (rdTo b, RelOne) else find1 xs
      find2 []         = error "No relation by name"
      find2 ((a,b):xs) = if nnsName a == s then (rdFrom b, RelMany) else find2 xs

  restMandatory' :: Eq s => (s -> FldDef' s) -> TabDef' s -> [s] -> [s]
  restMandatory' f td recFlds =
    L.filter (isMandatory . f) (tdFlds td) L.\\ recFlds
    where
      isMandatory fd = not (fdNullable fd || fdHasDefault fd)

  restPK' :: Eq s => TabDef' s -> [s] -> [s]
  restPK' td recFlds = tdKey td L.\\ recFlds
  |]


type NameNSK = NameNS' Symbol
type TypDefK = TypDef' Symbol
type FldDefK = FldDef' Symbol
type TabDefK = TabDef' Symbol
type RelDefK = RelDef' Symbol
type RecFieldK = RecField' Symbol
type RefK = Ref' Symbol

type NameNS = NameNS' Text
type TypDef = TypDef' Text
type FldDef = FldDef' Text
type TabDef = TabDef' Text
type RelDef = RelDef' Text

infixr 9 ->>
(->>) :: Text -> Text -> NameNS
(->>) = NameNS

type ns ->> name = 'NameNS ns name

type SimpleType c = 'TypDef c 'Nothing '[]

simpleType :: Text -> TypDef
simpleType c = TypDef c Nothing []

type SymNat = (Symbol, Nat)

type KnownSymNat sn = (SingI (NameSymNat sn))

nameSymNat :: forall sn -> KnownSymNat sn => Text
nameSymNat sn = demote @(NameSymNat sn)
-- >>> nameSymNat ("test", 42)
-- "test___42"

type NameSymNat (sn :: SymNat) = If (Snd sn == 0) (Fst sn)
  (AppendSymbol (Fst sn) (AppendSymbol "___" (Show_ (Snd sn))))

-- CTypDef
-- | instances will be generated by TH or codegen
class
  (ToStar name, ToStar (TTypDef sch name)) => CTypDef sch (name :: NameNSK) where

  type TTypDef sch name :: TypDefK

genDefunSymbols [''TTypDef]

-- | Schema-level field kind for (sch, tab, field name).
-- Instances are generated by codegen (Gen) or defined manually (e.g. Catalog).
-- Use 'TDBFieldInfo' to get 'RecFieldK' directly; use 'GetFldDef' / 'getFldDef' for plain field def.
class
      CDBFieldInfo sch (tab :: NameNSK) (name :: Symbol) where
  type TDBFieldInfo sch tab name :: RecFieldK NameNSK

genDefunSymbols [''TDBFieldInfo]

-- | Extract 'FldDefK' from a plain field kind (for conditions, order, etc.).
class CPlainFldDef (r :: RecFieldK NameNSK) where
  type PlainFldDef (r :: RecFieldK NameNSK) :: FldDefK
instance CPlainFldDef ('RFPlain fd) where
  type PlainFldDef ('RFPlain fd) = fd

-- | Field definition for (sch, tab, name) when the field is plain. Used by Select/Update conditions.
type family GetFldDef (sch :: k) (tab :: NameNSK) (name :: Symbol) :: FldDefK where
  GetFldDef sch tab name = PlainFldDef (TDBFieldInfo sch tab name)

genDefunSymbols [''GetFldDef]

-- CTabDef
-- | instances will be generated by TH or codegen
class
  ( ToStar name, ToStar (TTabDef sch name)
  , ToStar (SP.Map (GetFldDefSym2 sch name) (TdFlds (TTabDef sch name)))
  , ToStar (SP.Map (GetFldDefSym2 sch name) (TdKey (TTabDef sch name)))
  , ToStar
    (SP.Map (SP.MapSym1 (GetFldDefSym2 sch name)) (TdUniq (TTabDef sch name)))
  , ToStar
    ( ConcatMap (MapSym1 (GetFldDefSym2 sch name)) (TdUniq (TTabDef sch name)) )
  ) => CTabDef sch (name::NameNSK) where

  type TTabDef sch name :: TabDefK

-- | Extract (fromName, toName) from a Ref (for RelDef column list).
type family RefFromTo (r :: RefK) :: (Symbol, Symbol) where
  RefFromTo ('Ref fn _fd1 tn _fd2) = '(fn, tn)

-- | Extract FldDef from a Ref (fromDef).
type family RefFromDef (r :: RefK) :: FldDefK where
  RefFromDef ('Ref _ fd _ _) = fd

-- | Type-level logical Or for Bool (avoids conflict with SP.Or).
type family OrBool (a :: Bool) (b :: Bool) :: Bool where
  OrBool 'True _ = 'True
  OrBool 'False b = b

-- | Whether any ref in the list has a nullable column (fromDef).
type family HasNullableRefs (refs :: [RefK]) :: Bool where
  HasNullableRefs '[] = 'False
  HasNullableRefs (r ': rs) = OrBool (FdNullable (RefFromDef r)) (HasNullableRefs rs)

type family RefsToCols (refs :: [RefK]) :: [(Symbol, Symbol)] where
  RefsToCols '[] = '[]
  RefsToCols (r ': rs) = RefFromTo r ': RefsToCols rs

-- | Extract RelDef from a relation field (RFToHere / RFFromHere). Class avoids stuck TF on non-relation fields.
class CRelFldDef (r :: RecFieldK NameNSK) (tab :: NameNSK) where
  type RelDefFromField r tab :: RelDefK
instance CRelFldDef ('RFToHere fromTab refs) tab where
  type RelDefFromField ('RFToHere fromTab refs) tab = 'RelDef fromTab tab (RefsToCols refs)
instance CRelFldDef ('RFFromHere toTab refs) tab where
  type RelDefFromField ('RFFromHere toTab refs) tab = 'RelDef tab toTab (RefsToCols refs)

-- | RelDef for (sch, tab, name) when the field is a relation (for value-level or when tab is known).
type family GetRelDef (sch :: k) (tab :: NameNSK) (name :: Symbol) :: RelDefK where
  GetRelDef sch tab name = RelDefFromField (TDBFieldInfo sch tab name) tab

-- | Relation definition for relation name ref. Instances in codegen/Catalog.
type family TRelDef (sch :: k) (ref :: NameNSK) :: RelDefK

genDefunSymbols [''TTabDef, ''TRelDef]

type GetTypDef sch tab fld = TTypDef sch (FdType (GetFldDef sch tab fld))

type GetTypCategory sch tab fld = TypCategory (GetTypDef sch tab fld)

getFldDef
  :: forall sch t n
  . (CDBFieldInfo sch t n, ToStar (TDBFieldInfo sch t n)
    , CPlainFldDef (TDBFieldInfo sch t n))
  => FldDef
getFldDef = case demote @(TDBFieldInfo sch t n) of
  RFPlain fd -> fd
  _ -> error "impossible"

class CTabRels sch (tab :: NameNSK) where
  type TFrom sch tab :: [NameNSK]
  type TTo sch tab :: [NameNSK]

genDefunSymbols [''TFrom, ''TTo]

type RestMandatory sch t rs =
  RestMandatory' (GetFldDefSym2 sch t) (TTabDef sch t) rs

type RestPK sch t rs = RestPK' (TTabDef sch t) rs

promote [d|
  map2 :: (a -> b) -> [a] -> [(a,b)]
  map2 f = L.map (\a -> (a, f a))

  map3 :: (b -> c) -> (a -> [b]) -> [a] -> [[(b,c)]]
  map3 f g = L.map (map2 f . g)

  |]


type TTabRelFrom sch tab = Map2 (TRelDefSym1 sch) (TFrom sch tab)
type TTabRelTo sch tab = Map2 (TRelDefSym1 sch) (TTo sch tab)

-- | instances will be generated by TH
class
  ( ToStar (TTabs sch)
  , ToStar (TTabRelFroms sch)
  , ToStar (TTabRelTos sch)
  , ToStar (TTabFldDefs sch)
  , ToStar (TTabFlds sch)
  , ToStar (TTabDefs sch)
  , ToStar (TTypes sch)
  , ToStar (SP.Map (TTypDefSym1 sch) (TTypes sch))
  )
  => CSchema sch where

  type TTabs sch    :: [NameNSK]
  type TTypes sch   :: [NameNSK]

type TTabDefs sch = SP.Map (TTabDefSym1 sch) (TTabs sch)
type TTabFlds sch = SP.Map TdFldsSym0 (TTabDefs sch)

type family TTabFldDefsList sch (tabs :: [NameNSK]) (tabFlds :: [[Symbol]]) :: [[FldDefK]] where
  TTabFldDefsList sch '[] '[] = '[]
  TTabFldDefsList sch (t ': ts) (f ': fs) = SP.Map (GetFldDefSym2 sch t) f ': TTabFldDefsList sch ts fs

type TTabFldDefs sch = TTabFldDefsList sch (TTabs sch) (TTabFlds sch)
type TTabRelFroms sch = Map3 (TRelDefSym1 sch) (TFromSym1 sch) (TTabs sch)
type TTabRelTos sch = Map3 (TRelDefSym1 sch) (TToSym1 sch) (TTabs sch)

--
data TabInfo = TabInfo
  { tiDef  :: TabDef
  , tiFlds :: M.Map Text FldDef
  , tiFrom :: M.Map NameNS RelDef
  , tiTo   :: M.Map NameNS RelDef }
  deriving (Show, Eq)

tabInfoMap :: forall sch. CSchema sch => M.Map NameNS TabInfo
tabInfoMap = M.fromList
  [ (tabName, tabInfo)
  | tabName <- demote @(TTabs sch)
  | tabInfo <-
    [ TabInfo{..}
    | tiDef <- demote @(TTabDefs sch)
    | tiFlds <-
      [ M.fromList $ L.zip fs ds
      | fs <- demote @(TTabFlds sch)
      | ds <- demote @(TTabFldDefs sch) ]
    | tiFrom <- M.fromList <$> demote @(TTabRelFroms sch)
    | tiTo <- M.fromList <$> demote @(TTabRelTos sch)
    ]
  ]

typDefMap :: forall sch. CSchema sch => M.Map NameNS TypDef
typDefMap = M.fromList $ L.zip
  (demote @(TTypes sch)) (demote @(SP.Map (TTypDefSym1 sch) (TTypes sch)))

type TRelTab sch t name = GetRelTab
  (Map2 (TRelDefSym1 sch) (TFrom sch t)) (Map2 (TRelDefSym1 sch) (TTo sch t))
  name

type family TabOnPath2 sch (t :: NameNSK) (path :: [Symbol]) :: (NameNSK, RelType) where
  TabOnPath2 sch t '[] = '(t, 'RelMany)
  TabOnPath2 sch t '[x] = TRelTab sch t x
  TabOnPath2 sch t (x ': xs) = TabOnPath2 sch (Fst (TRelTab sch t x)) xs

type TabOnPath sch (t :: NameNSK) (path :: [Symbol]) = Fst (TabOnPath2 sch t path)

--
type family TabPath sch (t :: NameNSK) (path :: [Symbol]) :: Constraint where
  TabPath sch t '[] = ()
  TabPath sch t (x ': xs) = TabPath sch (Fst (TRelTab sch t x)) xs

type RecField = RecField' Text
type Ref = Ref' Text

-- | Value-level: whether any ref in the list has a nullable column.
-- Companion to type-level 'HasNullableRefs'.
hasNullableRefs :: [Ref] -> Bool
hasNullableRefs = L.any (fdNullable . fromDef)

type s := t = Tagged s t
infixr 5 :=

(=:) :: forall b. forall a -> b -> a := b
(=:) _ = coerce
infixr 5 =:

qualName :: NameNS -> Text
qualName NameNS {..}
  | nnsNamespace == fromString "pg_catalog" = nnsName
  | otherwise = nnsNamespace <> fromString "." <> nnsName
